---
title: "Baumgartner Disease and Phylogroups"
author: "Katherine Mueller"
date: "10/19/2021"
output: html_document
---

#Load Libraries
```{r}
library(phyloseq)
library(cowplot)
library(car)
library(readr)
library(dplyr)
```

#Define Paths
```{r}
phylogroups.rds <- "../../Data/Analysis/baumgartner_wPhylogroups.rds"
out.dir <- "../../Data/Analysis"
```

#Load and Check Phyloseq Object
```{r}
phylogroups.ps = read_rds(phylogroups.rds)
print(phylogroups.ps)
```

```{r}
sample_variables(phylogroups.ps)
```

#Analysis
Individuals are divided between that with IBS, those with UC, and healthy controls.
```{r}
unique(sample_data(phylogroups.ps)$Cohort)
```
Export sample data for visualization
```{r}
sample_data <- sample_data(phylogroups.ps) %>%
  as.matrix() %>%
  as.data.frame()

sample_data$Akk_abund <- as.numeric(sample_data$Akk_abund)
sample_data$AmI_abund <- as.numeric(sample_data$AmI_abund)
sample_data$AmII_abund <- as.numeric(sample_data$AmII_abund)
sample_data$AmIV_abund <- as.numeric(sample_data$AmIV_abund)
```

```{r}
write.csv(sample_data, file.path(out.dir, "baumgartner_phylogroup_dataframe.csv"))
```

#Session Info
```{r}
sessionInfo()
```
