---
title: "Baumgartner Akkermansia ASVs"
author: "Katherine Mueller"
date: "10/14/2021"
output: html_document
---

#Load Libraries
```{r}
library(phyloseq)
library(readr)
library(dplyr)
library(tidyr)
library(ggplot2)
```

#Define Paths
```{r}
baumgartner.rds <- "../../Data/Analysis/baumgartner.rds"
out.dir <- "../../Data/Analysis"
```

Load and check phyloseq object
```{r}
baumgartner.ps = read_rds(baumgartner.rds)
print(baumgartner.ps)
```

```{r}
sample_variables(baumgartner.ps)
```

#Relative Abundance
```{r}
rel.ps <- baumgartner.ps %>%
  transform_sample_counts(function(x) x/sum(x))
```

#Akkermansia ASV Identification
```{r}
akks.ps <- rel.ps %>%
  subset_taxa(Genus == "Akkermansia")
print(akks.ps)
```

Filter for Akk ASVs at a mean abundance of at least 0.01%
```{r}
mean_cutoff = 0.0001
mean_test = function(x) {
  mean(x) >= mean_cutoff
}

akks.0001mean.ps <- akks.ps %>%
  filter_taxa(mean_test, prune = TRUE)
print(akks.0001mean.ps)
```

Double check that none of the other ASVs should be included
```{r}
#Get dataframe for akk ASV abundances
all_akks <- akks.ps %>%
  otu_table() %>%
  as.data.frame()

#Make the dataframe long for plotting
akks.long <- all_akks %>%
  gather(ASV, Abundance)

#Plot Akk ASV abundances
akks.boxplot <- akks.long %>%
  ggplot(aes(x = ASV, y = Abundance)) +
  geom_point() +
  geom_jitter()
akks.boxplot
```

