---
title: "Gopalakrishnan Demux Dada"
author: "Katherine Mueller"
date: "7/30/2021"
output: html_document
---

#Load Libraries
```{r}
library(readr)
library(fs)
library(dplyr)
library(tibble)
library(Biostrings)
library(dada2)
library(stringr)
library(magrittr)
library(ggplot2)
library(tidyr)
library(phyloseq)
```

#Set up Paths, Directories, and Shell Variables
```{r}
#Directories
data.dir = "/work/kdm65/gopalakrishnan"
output.dir = "/work/kdm65/scratch"
```

```{r}
if (dir_exists(output.dir)) {
  dir_delete(output.dir)
}
dir_create(output.dir)
```

```{r}
demux.dir = file.path(output.dir, "demux")

#Files
map.file = file.path(data.dir, "Gopalakrishnan_map.txt")
silva.ref = file.path(data.dir, "silva_nr99_v138.1_wSpecies_train_set.fa.gz")
ps.rds = file.path(data.dir, "gopalakrishnan.rds")
```

#Filter and Trim
Get lists of forward and reverse reads
```{r}
fnFs <- sort(list.files(demux.dir, pattern = "_1.fastq.gz", full.names = TRUE))
fnRs <- sort(list.files(demux.dir, pattern = "_2.fastq.gz", full.names = TRUE))

forward_fastq_suffix = "_1.fastq.gz"

fnFs %>%
  basename %>%
  str_replace(forward_fastq_suffix,"") ->
  sample.names
```

```{r}
print(fnFs)
```

```{r}
print(fnRs)
```

```{r}
print(sample.names)
```

#Quality Profiles
```{r}
plotQualityProfile(fnFs[1:2])
```

```{r}
plotQualityProfile(fnRs[1:2])
```

#Filter Reads
Assign filepaths for filtered files
```{r}
filt_path <- file.path(output.dir, "filtered")
filtFs <- file.path(filt_path, paste0(sample.names, "_F_filt.fastq.gz"))
filtRs <- file.path(filt_path, paste0(sample.names, "_R_filt.fastq.gz"))
```

Filter Reads
```{r}
filt.out <- ffilterAndTrim(fnFs, filtFs, fnRs, filtRs, trimLeft = 10, truncLen = c(),
                           maxN = 0, maxEE = c(2,2), truncQ = 2, rm.phix = TRUE,
                           compress = TRUE, multithread = FALSE)
```

```{r}
head(filt.out)
```

#Learn Error Rates
```{r}
errF <- learnErrors(filtFs, multithread = FALSE)
errR <- learnErrors(filtRs, multithread = FALSE)
```

```{r}
plotErrors(errF, nominalQ = TRUE)
```

#Dereplication
```{r}
derepFs <- derepFastq(filtFs, verbose = TRUE)
derepRs <- derepFastq(filtRs, verbose = TRUE)
names(derepFs) <- sample.names
names(derepRs) <- sample.names
```

#Sample Inference
```{r}
dadaFs <- dada(derepFs, err=errF, multithread = FALSE)
dadaRs <- dada(derepRs, err=errR, multithread = FALSE)
```

```{r}
dadaFs[[2]]
```

