---
title: "IBDMDB Stool Demux DADA2"
author: "Katherine Mueller"
date: "8/6/2021"
output: html_document
---

#Load Libraries
```{r}
library(readr)
library(fs)
library(dplyr)
library(tibble)
library(Biostrings)
library(dada2)
library(stringr)
library(magrittr)
library(ggplot2)
library(tidyr)
library(phyloseq)
```

#Set up Paths, Directories, and Shell Variables
```{r}
#Directories
data.dir = "/work/kdm65/IBDMDB_stool"
output.dir = "/work/kdm65/scratch"
```

```{r}
if (dir_exists(output.dir)) {
  dir_delete(output.dir)
}
dir_create(output.dir)
```

```{r}
demux.dir = file.path(output.dir, "demux")

#Files
map.file = file.path(data.dir, "IBDMDB_stool_map.txt")
silva.ref = file.path(data.dir, "../silva_nr99_v138.1_wSpecies_train_set.fa.gz")
ps.rds = file.path(data.dir, "../IBDMDB_stool.rds")
sample.ids = file.path(data.dir, "sample_id.txt")

#Bash variables
Sys.setenv(RAW_FASTQ_DIR = data.dir)
```

#Demultiplexing
```{bash}
run_path=/work/kdm65/IBDMDB_stool
cd $run_path
for sam in `less sample_id.txt`
do
  echo $sam
  less /work/kdm65/IBDMDB_stool/42732_seqs.fastq | grep $sam -A 3 > $sam.fastq
done
```

